team:
   name: Cloudians
   members:
      - user: af.ariasr@uniandes.edu.co
        percentage: 0
      - user: j.charryg@uniandes.edu.co
        percentage: 30
      - user: d.granadam@uniandes.edu.cox`
        percentage: 40
      - user: v.escobar1@uniandes.edu.co
        percentage: 30
board: https://github.com/orgs/MISW-4301-Desarrollo-Apps-en-la-Nube/projects/108
user-management:
  folder: users
  port: 3000
  authors:
    - d.granadam@uniandes.edu.co
post-management:
  folder: posts
  port: 3000
  authors:
    - j.charryg@uniandes.edu.co
offer-management:
  folder: offer
  port: 3000
  authors:
    - af.ariasr@uniandes.edu.co
route-management:
  folder: routes
  port: 3000
  authors:
    - v.escobar1@uniandes.edu.co
