team:
   name: Cloudians
   members:
      - user: af.ariasr@uniandes.edu.co
        percentage: 0
      - user: j.charryg@uniandes.edu.co
        percentage: 30
      - user: d.granadam@uniandes.edu.co
        percentage: 40
      - user: v.escobar1@uniandes.edu.co
        percentage: 30
board: https://github.com/orgs/MISW-4301-Desarrollo-Apps-en-la-Nube/projects/108
url: 34.149.221.138
credit-cards:
  folder: creditcards
  port: 8000
  authors:
    - d.granadam@uniandes.edu.co
users:
  folder: users
  port: 3000
  authors:
    - d.granadam@uniandes.edu.co
    - j.charryg@uniandes.edu.co
utility:
  folder: utility
  port: 8000
  authors:
    - d.granadam@uniandes.edu.co
entrega2:
  folder: entrega2
  port: 8000
  authors:
    - d.granadam@uniandes.edu.co
    - j.charryg@uniandes.edu.co
    - v.escobar1@uniandes.edu.co
posts:
  folder: posts
  port: 3000
  authors:
    - j.charryg@uniandes.edu.co
offers:
  folder: offer
  port: 3000
  authors:
    - af.ariasr@uniandes.edu.co
routes:
  folder: routes
  port: 3000
  authors:
    - v.escobar1@uniandes.edu.co

