# Testing environment docker compose
version: '3.8'
services:
  testing-postgres-users:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "13001:5432"
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d