name: Test coverage
on:
  push:
    branches: 
      - main
      - develop
      - feature/49
jobs:
  test_users:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: users_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        working-directory: ./users
        run: pip install pipenv
      - name: Install psycopg2
        working-directory: ./users
        run: pip install psycopg2
      - name: Install dependencies
        working-directory: ./users
        run: pipenv install --dev
      - name: Run unit tests
        working-directory: ./users
        env:
          DB_NAME: users_test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: postgres
        run: pipenv run pytest --cov=src -v -s --cov-fail-under=70
  test_offers:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: offers_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        working-directory: ./offers
        run: pip install pipenv
      - name: Install psycopg2
        working-directory: ./offers
        run: pip install psycopg2
      - name: Install dependencies
        working-directory: ./offers
        run: pipenv install --dev
      - name: Run unit tests
        working-directory: ./offers
        env:
          DB_NAME: offers_test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: postgres
          USERS_PATH: http://users
        run: pipenv run pytest --cov=src -v -s --cov-fail-under=70
  test_routes:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: routes_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        working-directory: ./routes
        run: pip install pipenv
      - name: Install psycopg2
        working-directory: ./routes
        run: pip install psycopg2
      - name: Install dependencies
        working-directory: ./routes
        run: pipenv install --dev
      - name: Run unit tests
        working-directory: ./routes
        env:
          DB_NAME: routes_test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: postgres
          USERS_PATH: http://users
        run: pipenv run pytest --cov=src -v -s --cov-fail-under=70
  test_posts:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: posts_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        working-directory: ./posts
        run: pip install pipenv
      - name: Install psycopg2
        working-directory: ./posts
        run: pip install psycopg2
      - name: Install dependencies
        working-directory: ./posts
        run: pipenv install --dev
      - name: Run unit tests
        working-directory: ./posts
        env:
          DB_NAME: posts_test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: postgres
          USERS_PATH: http://users
        run: pipenv run pytest --cov=src -v -s --cov-fail-under=70
  test_utility:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: utilities_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        working-directory: ./utility
        run: pip install pipenv
      - name: Install psycopg2
        working-directory: ./utility
        run: pip install psycopg2
      - name: Install dependencies
        working-directory: ./utility
        run: pipenv install --dev
      - name: Run unit tests
        working-directory: ./utility
        env:
          DB_NAME: utilities_test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: postgres
          USERS_PATH: http://users
        run: pipenv run pytest --cov=src -v -s --cov-fail-under=70
